### PR TITLE
Syntax definition improvement and pane background colors.

### PR DESCRIPTION
**Pull request by luismendozamx**
Hi @wesbos 
Some minor upgrades made to match the Sublime version and improve the panels in Atom

Changes:
- Syntax for html attributes set to yellow.
- Syntax for js class definition improved.
- Background colors for bottom panel (find) and search results set correctly.
- Function calls, html entities and constants in objects matched

### CODE REVIEW

**Comment by wesbos** [comment]
Awesome! @rosston is the daddy of this theme so I'll ask him to merge it if everything is good

**Comment by luismendozamx** [comment]
With the changes the syntax looks just like the photo in https://github.com/wesbos/cobalt2/issues/103#issuecomment-222156751

Except for the `React.Component`, but I think due to meta names in atom there is no way to difference it from the name of the class.

Screenshot here:
screen shot 2016-06-23 at 8 13 58 pm

**Comment by rosston** [comment]
Thanks @wesbos! And thank you to @luismendozamx for the changes, of course. 

I am/have been computer-less for a few days, so I haven't been able to try these changes in Atom yet. For what it's worth, I haven't done the changes in this PR myself yet because I'm waiting for https://github.com/wesbos/cobalt2/pull/108 to get merged. Anyway, I'll try out these changes as soon as I'm able (hopefully within a couple days). 

A couple notes even without using the code:
- The version bump happens when I actually publish to Atom (and I'll probably go to 0.4.0 anyway), so the package.json and readme changes shouldn't be in the PR. If you throw the readme notes in a comment here, then I'll make sure they make it in. 
- Atom distinguishes between syntax and UI themes, and this is just a syntax theme. So I don't think the styles for the bottom panel should be included, as that would be best put in a UI theme.

Related to that last point @luismendozamx, what UI theme do you use with cobalt2?

**Comment by luismendozamx** [comment]
Thanks @rosston! You are right, the panel colors shouldn't be included. 

I'm currently using One Dark for this theme. 

I removed the changes to the Changelog and the version bump. The proposed comments for the Changelog would be:
- Fix html attribute color to match [Sublime Text version](https://github.com/wesbos/cobalt2)
- Fix js class definition color to match [Sublime Text version](https://github.com/wesbos/cobalt2)

Let me know if there is anything else that needs to be changed to merge the PR once https://github.com/wesbos/cobalt2/pull/108 is merged.

**Comment by rosston** [comment]
Tested in Atom, and it looks fine to me as is. If you could just rebase it down to 1 or 2 commits, then that'd be great. I think 9e569d4 and b6a54e7 are the only commits that actually have content in them if you rebase.

**Comment by luismendozamx** [comment]
Thanks @rosston! I squashed the commits to one. Had to force push, sorry about that.

**Comment by rosston** [comment]
Closing because I think I handled all these changes when updating from the Sublime version (in 0.4.0).

@luismendozamx, if there's anything I missed here, feel free to reopen!

**Comment by rosston** [comment]
^ Or, you know, ask me to reopen the PR, because _obviously_ I know how GitHub works. 😄

**Pull request closed without merging**
