### PR TITLE
Upgrade for Atom 1.0 / pull in changes from Sublime version

### PR DESCRIPTION
**Pull request by rosston**
- Changed stylesheets folder and updated selectors to get rid of Deprecation Cop warnings.
- Fixed some styles mangled by Atom's TextMate theme converter.
- Pulled in style changes from the Sublime version.

Generally speaking, these changes make the Atom version work and bring it closer to the Sublime version.

### CODE REVIEW

**Comment by rosston** [comment]
@wesbos I expect to actively maintain my fork of cobalt2-atom. Would you be interested in merging my fork and publishing an Atom package via your repo? Or should I go ahead and publish out of my own repo?

**Comment by wesbos** [comment]
Oh wow - I totally missed this. I'm so sorry! 

I can publish it from this repo -I'll even give you write access to it so you can keep it up to date. 

Where do I submit a theme for Atom? 

Thanks a ton for doing this!

**Comment by rosston** [comment]
No worries! And thanks for the write access! I forgot about this PR for a long time too. :)

You use the `apm` command installed with Atom to publish it. I can try to do it myself. I think it'll work fine since I have write access.

**Comment by wesbos** [comment]
That would be great! 

Can you update the readme to say how to install it once it's in apm? 

And give yourself credit / linkbacks to whatever you want :)

**Comment by rosston** [comment]
Absolutely! I plan to throw in a screenshot or two as well.

**Comment by wesbos** [comment]
You michiganers are alright👌👌👌👌👌

**Pull request merged**
