### PR TITLE
make js object keys mint color

### PR DESCRIPTION
**Pull request by amaldare93**
Updating based on last update to the sublime theme

### CODE REVIEW

**Comment by rosston** [comment]
Thanks! The code looks good to me, but I haven't had a chance to try it out in Atom yet. I'll shoot for doing that (and bringing in all the other Sublime changes) tonight.

**Comment by rosston** [comment]
Odd, this change appears to have no effect in Atom. Even more odd, I'm not seeing a difference in Sublime Text either (see https://github.com/wesbos/cobalt2/issues/107). I'll hold off on merging this until that Sublime Text issue has been resolved.

**Comment by wesbos** [comment]
Aye - I'll have a look at this. I use the babel highlighter so maybe I goofed the scopes up

**Comment by rosston** [comment]
JS object keys are now minty in 0.4.0 (albeit only with [language-babel](https://atom.io/packages/language-babel)).

**Pull request closed without merging**
